//
//  SyntaxTree.swift
//  GrammarParsing
//
//  Created by Ulf Akerstedt-Inoue on 2023/09/06.
//  Copyright © 2023 hakkabon software. All rights reserved.
//

import Foundation

/// A tree that can store different types of values in its leafs.
///
/// - leaf: Leaf node
/// - node: Internal node with with an arbitrary list of child elements (derivations).
/// - empty: An empty tree.
public enum SyntaxTree<Node: Equatable, Leaf: Equatable> {
    /// A leaf storing a leaf element
    case leaf(Leaf)

    /// A node with an arbitrary list of child elements (derivations).
    indirect case node(Node, children: [SyntaxTree<Node, Leaf>])
    
    /// Represents the initial state or a placeholder.
    /// Useful for the bottom of the parser stack.
    case empty
}

public extension SyntaxTree {
    
    /// Creates a new syntax tree node with a given node and a list of children
    ///
    /// - Parameters:
    ///   - node: Root node
    ///   - children: Children of the root node
    init(node: Node, children: [SyntaxTree<Node, Leaf>]) {
        self = .node(node, children: children)
    }
    
    /// Creates a new syntax tree with a given root node and no children
    ///
    /// - Parameter node: Root node
    init(node: Node) {
        self = .node(node, children: [])
    }
    
    /// Creates a new syntax tree with a given leaf value
    ///
    /// - Parameter value: Leaf value
    init(value: Leaf) {
        self = .leaf(value)
    }
}

public extension SyntaxTree {
    
    /// Returns the root node of the tree or nil if no root node exists
    var root: Node? {
        guard case .node(let node, children: _) = self else {
            return nil
        }
        return node
    }
    
    /// Returns the value stored in the current node if the current node is a leaf. Otherwise, nil is returned
    var leaf: Leaf? {
        guard case .leaf(let leaf) = self else {
            return nil
        }
        return leaf
    }
    
    /// Returns the direct children of the root node
    var children: [SyntaxTree<Node, Leaf>]? {
        guard case .node(_, children: let children) = self else {
            return nil
        }
        return children
    }
}

public extension SyntaxTree {

	/// Generates a new syntax tree by applying the transform function to every inner node of the tree.
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every inner node.
	func mapNodes<Result>(_ transform: (Node) throws -> Result) rethrows -> SyntaxTree<Result, Leaf> {
		switch self {
		case .leaf(let leaf):
			return .leaf(leaf)
			
		case let .node(node, children: children):
			return try .node(transform(node), children: children.map{ try $0.mapNodes(transform) } )

        case .empty:
            return .empty
		}
	}
	
	/// Generates a new syntax tree by applying the transform function to every leaf of the tree.
	///
	/// - Parameter transform: Transform function
	/// - Returns: A tree generated by applying the transform function to every leaf value
	func mapLeafs<Result>(_ transform: (Leaf) throws -> Result) rethrows -> SyntaxTree<Node, Result> {
		switch self {
		case .leaf(let leaf):
			return try .leaf(transform(leaf))
			
		case let .node(node, children: children):
			return try .node(node, children: children.map{ try $0.mapLeafs(transform) } )

        case .empty:
            return .empty
		}
	}
	
	/// All leafs of the tree
	var leafs: [Leaf] {
		switch self {
		case .leaf(let leaf):
			return [leaf]
			
		case .node(_, children: let children):
			return children.flatMap{$0.leafs}

        case .empty:
            return []
		}
	}
	
	/// Filters the tree by removing all nodes and their corresponding subtrees if the given predicate is false
	///
	/// - Parameter predicate: Predicate to filter the tree
	/// - Returns: A tree generated by filtering out nodes for which the predicate returned false
	func filter(_ predicate: (Node) throws -> Bool) rethrows -> SyntaxTree<Node, Leaf>? {
		switch self {
		case .leaf(let element):
			return .leaf(element)
			
		case let .node(node, children: children) where try predicate(node):
			return try .node(node, children: children.compactMap{try $0.filter(predicate)})
			
		case .node(_, children: _):
			return nil

        case .empty:
            return nil
		}
	}
	
	/// Explodes nodes and passes all child nodes to the parent node if the given closure returns true
	///
	/// - Parameter shouldExplode: Determines if a node should be exploded
	/// - Returns: A tree generated by exploding nodes determined by the given predicate
	func explode(_ shouldExplode: (Node) throws -> Bool) rethrows -> [SyntaxTree<Node, Leaf>] {
		switch self {
		case .leaf:
			return [self]
			
		case let .node(node, children: children) where try shouldExplode(node):
			return try children.flatMap{try $0.explode(shouldExplode)}
			
		case let .node(node, children: children):
			return try [.node(node, children: children.flatMap{try $0.explode(shouldExplode)})]

        case .empty:
            return []
		}
	}
	
	/// Compresses the tree by exploding nodes which have exactly one child node
	///
	/// - Returns: Tree generated by compressing the current tree
	func compressed() -> SyntaxTree<Node, Leaf> {
		switch self {
		case .node(_, children: let children) where children.count == 1:
			let child = children[0]
			if case .leaf = child {
				return self
			} else {
				return child.compressed()
			}
			
		case let .node(node, children: children):
			return .node(node, children: children.map{ $0.compressed() })
			
		default:
			return self
		}
	}
	
	/// Returns all nodes which match the given predicate.
	///
	///
	/// - Parameter predicate: Predicate to match
	/// - Returns: A collection of nodes which match the given predicate
	func allNodes(where predicate: (Node) throws -> Bool) rethrows -> [SyntaxTree<Node, Leaf>] {
		switch self {
		case .leaf:
			return []
			
		case let .node(node, children: children) where try predicate(node):
			return try [self] + children.flatMap{try $0.allNodes(where: predicate)}
			
		case .node(_, children: let children):
			return try children.flatMap{ try $0.allNodes(where: predicate) }

        case .empty:
            return []
		}
	}
}

extension SyntaxTree: Equatable {
    
    /// Determines if two syntax trees are equal to each other.
    /// This function returns true, if both trees have the same structure, equal inner nodes and equal leafs
    ///
    /// - Parameters:
    ///   - lhs: First tree to compare
    ///   - rhs: Second tree to compare
    /// - Returns: A boolean value indicating whether the provided trees are equal to each other
    public static func == (lhs: SyntaxTree<Node, Leaf>, rhs: SyntaxTree<Node, Leaf>) -> Bool {
        switch (lhs, rhs) {
        case let(.leaf(lLeaf), .leaf(rLeaf)):
            return lLeaf == rLeaf
            
        case (.node(let lKey, children: let lChildren), .node(let rKey, children: let rChildren)):
            return lKey == rKey && lChildren.count == rChildren.count && !zip(lChildren, rChildren).map(==).contains(false)
            
        case (.empty, .empty):
            return true
            
        default:
            return false
        }
    }
}

extension SyntaxTree: CustomStringConvertible {

    /// Pretty print as a real tree
    public var description: String {
        return SyntaxTreePrinter.print(self)
    }
}
